package view;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */

import controller.CuacaController;
import controller.FileController;
import model.Cuaca;
import javax.swing.table.DefaultTableModel;
import model.LokasiFavorit;
import java.util.ArrayList;
import java.util.List;
import java.net.*;
import java.io.*;
import org.json.*;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class CekCuaca extends javax.swing.JFrame {
    private CuacaController cuacaController;
    private FileController fileController;
    private LokasiFavorit lokasiFavorit;
    private List<Cuaca> daftarCuaca;
    
    /**
     * Creates new form CekCuaca
     */
    
    public CekCuaca() {
        initComponents();
        cuacaController = new CuacaController();
        fileController = new FileController();
        lokasiFavorit = new LokasiFavorit();
        daftarCuaca = new ArrayList<>();
        isiKota();
    }
    
    private void isiKota() {
    cbKota.removeAllItems();
    for (String kota : lokasiFavorit.getDaftarFavorit()) {
        cbKota.addItem(kota);
    }
    if (cbKota.getItemCount() == 0) { // kalau belum ada data
        cbKota.addItem("Jakarta");
        cbKota.addItem("Surabaya");
        cbKota.addItem("Bandung");
        cbKota.addItem("Yogyakarta");
        cbKota.addItem("Denpasar");
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTambahFavorit = new javax.swing.JButton();
        btnCekCuaca = new javax.swing.JButton();
        txtKotaBaru = new javax.swing.JTextField();
        cbKota = new javax.swing.JComboBox<>();
        lblLokasi = new javax.swing.JLabel();
        btnFavorit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNamaKota = new javax.swing.JLabel();
        lblIconCuaca = new javax.swing.JLabel();
        lblKondisi = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        lblKelembapan = new javax.swing.JLabel();
        lblKecepatanAngin = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuaca = new javax.swing.JTable();
        btnSimpanCSV = new javax.swing.JButton();
        btnMuatData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Cek Cuaca ");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Aplikasi Cek Cuaca");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(367, 367, 367))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTambahFavorit.setText("Tambah ke Favorit");
        btnTambahFavorit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahFavoritActionPerformed(evt);
            }
        });

        btnCekCuaca.setText("Cek Cuaca");
        btnCekCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekCuacaActionPerformed(evt);
            }
        });

        cbKota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblLokasi.setText("Pilih Kota");

        btnFavorit.setText("Hapus dari Favorit");
        btnFavorit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoritActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblLokasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKotaBaru)
                    .addComponent(cbKota, 0, 200, Short.MAX_VALUE))
                .addGap(341, 341, 341))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCekCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambahFavorit)
                .addGap(18, 18, 18)
                .addComponent(btnFavorit)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLokasi)
                    .addComponent(cbKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKotaBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahFavorit)
                    .addComponent(btnCekCuaca)
                    .addComponent(btnFavorit))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblNamaKota.setText("Kota");

        lblIconCuaca.setText("Ikon");

        lblKondisi.setText("Kondisi");

        lblSuhu.setText("Suhu");

        lblKelembapan.setText("Kelembapan");

        lblKecepatanAngin.setText("Kecepatan Angin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNamaKota)
                    .addComponent(lblKondisi)
                    .addComponent(lblSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKelembapan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKecepatanAngin, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(lblIconCuaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblNamaKota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIconCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKondisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSuhu)
                .addGap(18, 18, 18)
                .addComponent(lblKelembapan)
                .addGap(18, 18, 18)
                .addComponent(lblKecepatanAngin)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblCuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kota", "Negara", "Suhu (°C)", "Cuaca", "Kelembapan (%)", "Kecepatan Angin (m/s)", "Waktu Cek"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCuaca);
        if (tblCuaca.getColumnModel().getColumnCount() > 0) {
            tblCuaca.getColumnModel().getColumn(0).setResizable(false);
        }

        btnSimpanCSV.setText("Simpan CSV");
        btnSimpanCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanCSVActionPerformed(evt);
            }
        });

        btnMuatData.setText("Muat Data");
        btnMuatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuatDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(btnSimpanCSV)
                .addGap(18, 18, 18)
                .addComponent(btnMuatData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanCSV)
                    .addComponent(btnMuatData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekCuacaActionPerformed
    try {
        String kota = cbKota.getSelectedItem().toString();
        Cuaca data = cuacaController.getDataCuaca(kota);

        // tampilkan ke label
        lblNamaKota.setText("Kota: " + data.getNamaKota() + ", " + data.getNegara());
        lblSuhu.setText("Suhu: " + data.getSuhu() + " °C");
        lblKelembapan.setText("Kelembapan: " + data.getKelembapan() + "%");
        lblKecepatanAngin.setText("Kecepatan Angin: " + data.getKecepatanAngin() + " m/s");
        lblKondisi.setText("Kondisi: " + data.getKondisi() + " (" + data.getDeskripsi() + ")");

        
         // ====== TAMPILKAN GAMBAR IKON CUACA ======
        try {
            java.net.URL url = new java.net.URL(data.getIconUrl());
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(url);
            lblIconCuaca.setIcon(icon);
        } catch (Exception ex) {
            lblIconCuaca.setIcon(null);
            lblIconCuaca.setText("Ikon tidak tersedia");
        }
        // tambahkan ke list dan tabel
        daftarCuaca.add(data);
        javax.swing.table.DefaultTableModel model = 
            (javax.swing.table.DefaultTableModel) tblCuaca.getModel();
        model.addRow(new Object[]{
            data.getNamaKota(),
            data.getNegara(),
            data.getSuhu(),
            data.getKondisi(),
            data.getKelembapan(),
            data.getKecepatanAngin(),
            data.getWaktu()
        });

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCekCuacaActionPerformed

    private void btnTambahFavoritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahFavoritActionPerformed
    int selectedIndex = cbKota.getSelectedIndex();

    if (selectedIndex == -1) {
        JOptionPane.showMessageDialog(this, "Pilih kota yang ingin dihapus terlebih dahulu!");
        return;
    }

    String kota = cbKota.getSelectedItem().toString();
    int konfirmasi = JOptionPane.showConfirmDialog(
        this,
        "Apakah kamu yakin ingin menghapus kota \"" + kota + "\" dari daftar?",
        "Konfirmasi Hapus Kota",
        JOptionPane.YES_NO_OPTION
    );

    if (konfirmasi == JOptionPane.YES_OPTION) {
        // Hapus dari combo box
        cbKota.removeItemAt(selectedIndex);

        // Hapus dari daftarFavorit dan simpan ke file
        LokasiFavorit lokasiFavorit = new LokasiFavorit(); // pastikan ini sama instance yang dipakai load awal
        lokasiFavorit.hapusFavorit(kota);
        lokasiFavorit.saveToFile();

        JOptionPane.showMessageDialog(this, "Kota \"" + kota + "\" berhasil dihapus dari daftar.");
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnTambahFavoritActionPerformed

    private void btnSimpanCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanCSVActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Simpan Data Cuaca");
    
    // Membuat filter agar hanya bisa simpan .csv
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("CSV Files", "csv"));

    int userSelection = fileChooser.showSaveDialog(this);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();

        // Pastikan file berekstensi .csv
        if (!fileToSave.getName().toLowerCase().endsWith(".csv")) {
            fileToSave = new File(fileToSave.getAbsolutePath() + ".csv");
        }

        try {
            fileController.simpanKeCSV(daftarCuaca, fileToSave); // versi baru dengan parameter File
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke " + fileToSave.getAbsolutePath());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
    }                                                      // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanCSVActionPerformed

    private void btnMuatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuatDataActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih File CSV Data Cuaca");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("CSV Files", "csv"));
        int userSelection = fileChooser.showOpenDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToOpen = fileChooser.getSelectedFile();
            DefaultTableModel model = (DefaultTableModel) tblCuaca.getModel();
            model.setRowCount(0); // kosongkan tabel lama

            try (BufferedReader reader = new BufferedReader(new FileReader(fileToOpen))) {
                String line;
                reader.readLine(); // skip header
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split(",");
                    if (parts.length == 8) {
                        Object[] row = new Object[]{
                            parts[0], parts[1],
                            Double.parseDouble(parts[2]),
                            parts[3],
                            Integer.parseInt(parts[5]),
                            Double.parseDouble(parts[6]),
                            parts[7]
                        };
                        model.addRow(row);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
            }
        }
  // TODO add your handling code here:
    }//GEN-LAST:event_btnMuatDataActionPerformed

    private void btnFavoritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritActionPerformed
    int selectedIndex = cbKota.getSelectedIndex();

    if (selectedIndex == -1) {
        JOptionPane.showMessageDialog(this, "Pilih kota yang ingin dihapus terlebih dahulu!");
        return;
    }

    String kota = cbKota.getSelectedItem().toString();
    int konfirmasi = JOptionPane.showConfirmDialog(
        this,
        "Apakah kamu yakin ingin menghapus kota \"" + kota + "\" dari daftar?",
        "Konfirmasi Hapus Kota",
        JOptionPane.YES_NO_OPTION
    );

    if (konfirmasi == JOptionPane.YES_OPTION) {
        // Hapus dari daftarFavorit dan simpan ke file
        lokasiFavorit.hapusFavorit(kota);
        lokasiFavorit.saveToFile();

        // Hapus dari combo box
        cbKota.removeItemAt(selectedIndex);

        JOptionPane.showMessageDialog(this, "Kota \"" + kota + "\" berhasil dihapus dari daftar.");
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btnFavoritActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekCuaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekCuaca;
    private javax.swing.JButton btnFavorit;
    private javax.swing.JButton btnMuatData;
    private javax.swing.JButton btnSimpanCSV;
    private javax.swing.JButton btnTambahFavorit;
    private javax.swing.JComboBox<String> cbKota;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIconCuaca;
    private javax.swing.JLabel lblKecepatanAngin;
    private javax.swing.JLabel lblKelembapan;
    private javax.swing.JLabel lblKondisi;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JLabel lblNamaKota;
    private javax.swing.JLabel lblSuhu;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCuaca;
    private javax.swing.JTextField txtKotaBaru;
    // End of variables declaration//GEN-END:variables
}
